[workspace]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]
preview = ["pixi-build"]

[activation.env]
PIXI_PROJECT_ROOT = "."

[dependencies]
website = { path = "." }
quarto = ">=1.7.31,<2"

[tasks]
render = { cmd = "quarto render" }
preview = { cmd = "quarto preview" }
publish = { cmd = "quarto publish --no-prompt" }
publish-github = { cmd = "quarto publish gh-pages" }

[package]
name = "website"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-python", version = "0.1.*" }

[package.host-dependencies]
hatchling = "==1.26.3"

[package.run-dependencies]
